over_object:
  header:
    seq: 0
    stamp:
      secs: 0
      nsecs: 0
    frame_id: 'base_link'
  pose:
    position:
      x: -0.2
      y: -1.1
      z: 0.443
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 0.0

object:
  header:
    seq: 0
    stamp:
      secs: 0
      nsecs: 0
    frame_id: 'base_link'
  pose:
    position:
      x: -0.2
      y: -1.1
      z: 0.1
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 0.0

home:
  header:
    seq: 0
    stamp:
      secs: 0
      nsecs: 0
    frame_id: 'base_link'
  pose:
    position:
      x: 0.366
      y: 0.157
      z: 0.443
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 0.0